### ISSUE TITLE
"RNColorMatrixImageFilter" was not found in the UIManager 0.57.2

### ISSUE THREAD

**Issue by wawrzy** [iyegoroff/react-native-color-matrix-image-filters#11]
Hi,

I'm facing the same issue that #7  on ReactNative 0.57.2.
But clean Xcode project doesn't work.

Any ideas ?

**Comment by sbtly** [comment]
Hi! After cleaning in Xcode, I also did the following steps.
react-community/react-native-maps#2495 (comment)

**Comment by iyegoroff** [comment]
This is unlikely related to rncmif itself and can be fixed with some general approach, as in comment above.

**Comment by wawrzy** [comment]
Finally I succeeded ! 🥇 

Thank you 👍
