### ISSUE TITLE
Could not find component config for native component

### ISSUE THREAD

**Issue by tushe-tv** [iyegoroff/react-native-color-matrix-image-filters#114]
On rn 0.73.0 (on Mac) I'm getting this error:
 
`[Error: TransformError node_modules/react-native-color-matrix-image-filters/dist/CMIFColorMatrixImageFilterNativeComponent.js: .../node_modules/react-native-color-matrix-image-filters/dist/CMIFColorMatrixImageFilterNativeComponent.js: Could not find component config for native component]`

This is the way of import:

`import {Grayscale} from 'react-native-color-matrix-image-filters';`

**Comment by cavanierc** [comment]
Hello, I have the same issue with rn 0.73.1 on Mac:
`error: node_modules/react-native-color-matrix-image-filters/dist/CMIFColorMatrixImageFilterNativeComponent.js: .... : Could not find component config for native component`

**Comment by diogo-andrade** [comment]
This PR https://github.com/iyegoroff/react-native-color-matrix-image-filters/pull/115 solves the problem. You can create a patch on your side while we wait for a new release.

**Comment by iyegoroff** [comment]
Fixed in v6.0.5

**Comment by Manikanta-duEITC** [comment]
We are getting again with react-native0.80.0, any solution?
