### ISSUE TITLE
save the edited image option

### ISSUE THREAD

**Issue by kotomono** [iyegoroff/react-native-color-matrix-image-filters#12]
is it possible to save the edited image (with original size)? if yes how? if no is there a workaround to follow? thanks

**Comment by iyegoroff** [comment]
Nope, this feature is not supported. Maybe you can use https://github.com/gre/react-native-view-shot to achieve this.

**Comment by Orxcle-xx** [comment]
But in this case it the quality will be bad..( the size of the image won't be preserved ).

**Comment by Orxcle-xx** [comment]
Is it possible somehow to get the image data? ( for example in base64 ).
Like that we could save it?

The library feels great, simple and powerful at the same time, but lack of export functionality greatly reduces its usage.

**Comment by iyegoroff** [comment]
I agree that would be a valuable feature. If something like "react-native-extract-data-from-image" exists it could be done relatively easy by providing `onDone` callback to indicate that filtering is finished.

- [ ] find or create a module for extracting data from image
- [ ] add `onDone` callback

**Comment by rown89** [comment]
I didn't find any library to do this, I really need to save images, someone have a solution?

**Comment by bozzmob** [comment]
I have the same problem, is there any way to save the images?

**Comment by iyegoroff** [comment]
Closing, this is now out of [scope](https://github.com/iyegoroff/react-native-color-matrix-image-filters#scope).

**Comment by maxximee** [comment]
If anyone is still wondering, here is how to save the image without losing quality:

const filteredImageRef = useRef<any>();
...
const filteredImageURI = await captureRef(filteredImageRef, {
        format: 'png',
        quality: 1,
        result: 'tmpfile',
        width: picWidth,
        height: picHeight,
      });
      await CameraRoll.save(filteredImageURI, {type: 'photo'});
...
      <ColorMatrix matrix={colorMatrix}>
        <Image
          ref={filteredImageRef}
          style={[styles.image, {height: imageHeight}]}
          source={{uri: sourceImg}}
        />
      </ColorMatrix>

**Comment by spinoza1791** [comment]
> If anyone is still wondering, here is how to save the image without losing quality:
> 
> const filteredImageRef = useRef(); ... const filteredImageURI = await captureRef(filteredImageRef, { format: 'png', quality: 1, result: 'tmpfile', width: picWidth, height: picHeight, }); await CameraRoll.save(filteredImageURI, {type: 'photo'}); ... <Image ref={filteredImageRef} style={[styles.image, {height: imageHeight}]} source={{uri: sourceImg}} />

can this be accomplished with useState instead of useRef? useRef itself is problematic for my version of RN.
