### ISSUE TITLE
Image fails to render when passed through ColorMatrix

### ISSUE THREAD

**Issue by CoffeeFlux** [iyegoroff/react-native-color-matrix-image-filters#121]
Platform: iOS
react-native: 0.73.2 (Expo 50)
Architecture: old

Cleaning does not help. This is a bare workflow.

Simple repro here: https://github.com/CoffeeFlux/expo-color-matrix-test

**Comment by iyegoroff** [comment]
There is no 'image' prop. Please check the [example](https://github.com/iyegoroff/react-native-color-matrix-image-filters?tab=readme-ov-file#example).
