### ISSUE TITLE
ColorMatrix component gives different result than the Web and Swift matrix.

### ISSUE THREAD

**Issue by blackazaru** [iyegoroff/react-native-color-matrix-image-filters#127]
The matrix in the web and the ColorMatrix component yield different results, whereas Swift's CIFilter 'CIColorMatrix' produces the same result as on the web. Do you have any ideas why?

**Versions:**
react: v18.2.0
react-native: v0.73.1
react-native-color-matrix-image-filters: v6.0.5
architecture : "old"

**Smartphone:**
Device: iPhone11
OS: IOS 17.3

**Screenshots:**

WEB:
<img width="992" alt="Screenshot at Mar 20 21-06-52" src="https://github.com/iyegoroff/react-native-color-matrix-image-filters/assets/6501334/11f56e35-c41e-48cb-9e81-4cd557e5ee75">

Swift:
![Swift](https://github.com/iyegoroff/react-native-color-matrix-image-filters/assets/6501334/b79e6f83-4fec-4763-8cdd-e59dd3088e36)

ColorMatrix:
![IMG_9972](https://github.com/iyegoroff/react-native-color-matrix-image-filters/assets/6501334/f68a6e87-72a3-4a7e-bff6-090274f83357)

**Comment by iyegoroff** [comment]
It is different because it uses Android-like [matrix format](https://github.com/iyegoroff/react-native-color-matrix-image-filters?tab=readme-ov-file#matrix-type).
