### ISSUE TITLE
Can add color bar to select color for image.

### ISSUE THREAD

**Issue by bharatidudhjiya** [iyegoroff/react-native-color-matrix-image-filters#13]
I am using this library with latest react native. 

Now I want,  user can select image color and apply this to image.

So, is there any way to give color choose option to end user, using this library.

And also want to save edited image.

Thanks!

**Comment by iyegoroff** [comment]
> So, is there any way to give color choose option to end user, using this library.
Not sure what did you mean by that. Anyway, all available APIs are listed in the README.md.

> And also want to save edited image.
#12
