### ISSUE TITLE
`<Grayscale>` not working with `expo-image`

### ISSUE THREAD

**Issue by pepew-le-boss** [iyegoroff/react-native-color-matrix-image-filters#131]
As simple as the title.

This works
```javascript
import { Image } from 'react-native';
import { Grayscale } from 'react-native-color-matrix-image-filters';

<Grayscale>
  <Image
    source={{
      uri: "someUri",
    }}
    style={{ height: 200, width: '100%' }}
  />
</Grayscale>
```

This doesn't work
```javascript
import { Image } from 'expo-image';
import { Grayscale } from 'react-native-color-matrix-image-filters';

<Grayscale>
  <Image
    source={{
      uri: "someUri",
    }}
    style={{ height: 200, width: '100%' }}
  />
</Grayscale>
```

**Comment by iyegoroff** [comment]
It was not designed to work with expo-image.

**Comment by AdamGerthel** [comment]
Would also love to see support for expo-image. [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) hasn't been maintained for over two years and expo-image has quickly become the standard replacement for when RN's `Image` isn't enough.

**Comment by iyegoroff** [comment]
Ok, expo-image is now supported starting from v7.0.0.

**Comment by iyegoroff** [comment]
Yes, only bare workflow is supported.
