### ISSUE TITLE
View config not found for name CMIFColorMatrixImageFilter

### ISSUE THREAD

**Issue by plowman** [iyegoroff/react-native-color-matrix-image-filters#14]
## Versions of things
Seen on Android Device running Android 6.0.1
react-native: 0.57.5
react-native-color-matrix-image-filters: 5.0.1

## Did I try cleaning the project?
Yes I did

## Stack trace
```
 Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager. This error is located at: 
 in CMIFColorMatrixImageFilter (at native-filter.js:11)
 in NativeFilter (at color-matrix-filter.js:15)
 in ColorMatrix (at color-matrix-filter.js:56)
 in Grayscale (at Avatar.js:189)
 in Avatar (at RequestDetails.js:170)
 in RCTView (at View.js:45)
 in RCTView (at View.js:45)
 in RCTScrollView (at ScrollView.js:977)
 in ScrollView (at RequestDetails.js:159)
 in RCTView (at View.js:45)
 in RCTView (at View.js:45)
 in NavigationContainer (at RequestDetails.js:142)
 in RequestDetails (at RequestDetails.js:109)
 in RequestDetailsContainer (at RequestDetailsLoader.js:76)
 in RequestDetailsLoader (at withNavigationContext.js:118)
 in WithNavigationContext(RequestDetailsLoader)
 (at withStoreProvider.js:16)
 in Provider (created by Consumer)
 in Consumer (created by Provider)
 in Provider (at withStoreProvider.js:15)
 in WithStateProvider(WithNavigationContext(RequestDetailsLoader)) (at ComponentWrapper.js:28)
 in WrappedComponent (at renderApplication.js:34)
 in RCTView (at View.js:45)
 in RCTView (at View.js:45)
 in AppContainer (at renderApplication.js:33)
```

## Repro Steps
1. `npm install react-native-color-matrix-image-filters --save`
2. `react-native link react-native-color-matrix-image-filters`

## Expected
* MainApplication.java should have a line in `getPackages()`, ` new ColorMatrixImageFiltersPackage()`.

## Actual
* MainApplication.java is missing that line.
* Adding that line fixes this issue.

Anyway, this library has been super useful for us so far, so thank you for that. I'm not sure what capabilities the `react-native link` tool has, but it would be great if the tool could update the MainApplication.java file as well.

**Comment by iyegoroff** [comment]
There was a breaking change in v5.0.0 - `RNColorMatrixImageFiltersPackage.java` was renamed to `ColorMatrixImageFiltersPackage.java`, so if were using pre-5.0.0 version of this package you have to run something like this:
```bash
react-native unlink react-native-color-matrix-image-filters
yarn upgrade react-native-color-matrix-image-filters@5.0.1
react-native link react-native-color-matrix-image-filters
```

**Comment by plowman** [comment]
Got it. 5.0.1 is the only version I've used on this project, so I'm not sure it's an upgrade issue. I also just checked the latest on npm, 5.0.12, and confirmed this is still an issue in that version.

Just to be sure, I undid my manual changes to MainApplication.java and then ran your commands above. The result was that MainApplication.java wasn't updated at all by the `react-native link` command.

Out of curiosity, is there a place in your code which describes which changes to make to the MainApplication.java file? Or is that something entirely handled by the `react-native` command based on whatever classes in your project implement `ReactPackage`? If it's the latter, maybe this is just a react-native bug.

**Comment by iyegoroff** [comment]
>The result was that MainApplication.java wasn't updated at all by the react-native link command.

Probably `react-native link` can fail if there are manual changes to affected files.

>Or is that something entirely handled by the react-native command based on whatever classes in your project implement ReactPackage?

Yes.

I just checked linking rncmif on a fresh project - and everything worked as intended, so I'm not sure if there is any error with this module.

**Comment by plowman** [comment]
Aha, that's good to know. In that case I'll close this. Thanks for looking into it.

**Comment by taqcuong1996** [comment]
Have any solution for this bug ??? I'm using expo and run it on simulator and got this bug. Please help me !

**Comment by plowman** [comment]
Hey @taqcuong1996 you're seeing this issue on the iOS simulator, is that right? If so, do you have a line in your Podfile that's something like `pod "RNColorMatrixImageFilters" ...`?

**Comment by taqcuong1996** [comment]
<img width="317" alt="Screen Shot 2019-04-03 at 8 36 26 AM" src="https://user-images.githubusercontent.com/40909257/55446895-c4dcf000-55eb-11e9-87f7-7ea257c840af.png">
Yes, I have a line like it in my pobfile. But now i am using expo to build react-native, so i don't think this bug from that, because i can build my project on simulator without ios and android folder (I create ios and android folder to build apk to test on real phone). I still not find any solution for it. But now i try to use gl-react for filter, and it worked successfully, you can try with it. My english is not good, thanks for reading and your repply :) :) :)

**Comment by Kngfhrr** [comment]
Hi! @plowman, I have the same problem like a @taqcuong1996 . The tips above do not help. What else could be the reason? Thanks!

**Comment by dbh21** [comment]
I see this issue as well after installing the latest and running in expo

**Comment by mr-fibonacci** [comment]
hi guys, is this library compatible with the expo managed workflow?

**Comment by Slapbox** [comment]
Seems the answer is no for Expo.

**Comment by shahidavalisyed** [comment]
> I see this issue as well after installing the latest and running in expo

Can any one Help?. I too got same in my android expo

**Comment by zohaib-ahmad1020** [comment]
Still facing similar issue in react native
