### ISSUE TITLE
ios build <Image/RCTImageUtils.h> not found

### ISSUE THREAD

**Issue by mllrmat** [iyegoroff/react-native-color-matrix-image-filters#15]
I am using react-native-color-matrix-image-filters filters in my react native app. 

Versions: 
react-native: 0.58.4
react-native-color-matrix-image-filters: 5.1.3

I am using a pod file to manage the ios dependencies. I also use firebase, so I cannot use the "use_frameworks!" directive. 

When I try to build on ios it fails with the error <Image/RCTImageUtils.h> not found in CMIFColorMatrixImageFilter.m. When I change the import to <React/RCTImageUtils.h> everything works file.

**Comment by iyegoroff** [comment]
Fixed in 5.1.4
