### ISSUE TITLE
Build issue for Gradle >= 5.0

### ISSUE THREAD

**Issue by alexciarlillo** [iyegoroff/react-native-color-matrix-image-filters#16]
As of Gradle 5.0 it appears that the internal classes are no longer implicitly imported (https://docs.gradle.org/5.0-milestone-1/release-notes.html#implicit-imports-for-internal-classes-have-been-removed).

This is causing an issue when attempting to check the GradleVersion in build.gradle

**Comment by iyegoroff** [comment]
Does replacing that check with`VersionNumber.parse(gradle.gradleVersion) >= VersionNumber.parse('4.1')` fix it?

**Comment by alexciarlillo** [comment]
It does not appear to. It results in a similar error:

```
> Could not get unknown property 'VersionNumber' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
