### ISSUE TITLE
Warning: Async Storage RN 0.59

### ISSUE THREAD

**Issue by joan-saum** [iyegoroff/react-native-color-matrix-image-filters#18]
Since React native 0.59, using the module `AsyncStorage` give this warning : 

> Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

**Comment by iyegoroff** [comment]
The library itself doesn't use AsyncStorage - https://github.com/iyegoroff/react-native-color-matrix-image-filters/tree/master/src , probably it is being imported somewhere in the example app or inside fable bindings.

**Comment by joan-saum** [comment]
Ok it was present in MatrixFilterConstructor/out/fable/Fable.Helpers.ReactNative.js when i was on v4.0.0. Upgrading to 5.1.5 delete this file and solve the problem.
