### ISSUE TITLE
iOS crashed with 5.1.7, fixed in 5.2.0

### ISSUE THREAD

**Issue by nchase** [iyegoroff/react-native-color-matrix-image-filters#24]
Just an FYI for anyone who may be having a bad time: our app crashed completely when we used the `<Grayscale>` component after upgrading to react-native 0.61. We were on library version `5.1.7`. 

The error looked something like `NSInvalidArgumentException · -[UIImage reactKeyframeAnimation]: unrecognized selector sent to instance`.

Upgrading to version `5.2.0` of the library fixed this for us – not exactly sure why, but wanted to share.

I don't know if there's any resolution that needs to be handled here (though I am curious about why this happened), mostly just wanted to add this here in case it could be useful to someone. Thanks for your great work!

**Comment by iyegoroff** [comment]
Hey, @nchase, thank you for your feedback!
