### ISSUE TITLE
need callback prop in all components to know that modified Image already visible

### ISSUE THREAD

**Issue by MikhailVasiliev** [iyegoroff/react-native-color-matrix-image-filters#25]
Versions: 
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-color-matrix-image-filters": "^5.2.0"

I work with Mapbox and I firstly draw custom markers -> then convert images to grayscaled -> then capture these markers -> then pass these images to Mapbox.

I need to dynamically capture the grayscaled image just after it appears already in grey shades but I don't have a callback for this purpose. If I try to make it in Image's onLoadEnd sometimes I get empty image. 

please add it to components (especially for Grayscale)

**Comment by iyegoroff** [comment]
Filtering is triggered when underlying native images changes, so onLoadEnd signals that filtering is just started. Despite applying color matrix filter is very fast on both platforms it is also asynchronous at the same time. So you can't say for sure that filtering will be always faster than receiving onLoadEnd event. Probably you can add some delay to onLoadEnd handler to resolve this issue.

**Comment by MikhailVasiliev** [comment]
> Filtering is triggered when underlying native images changes, so onLoadEnd signals that filtering is just started. Despite applying color matrix filter is very fast on both platforms it is also asynchronous at the same time. So you can't say for sure that filtering will be always faster than receiving onLoadEnd event. Probably you can add some delay to onLoadEnd handler to resolve this issue.

yes, I'm using the timeout, but that's the problem for me because I need to capture a grayscaled image as fast as possible. And now (with timeout) I always spend some extra time waiting to be sure that grayscaled image is already shown. I used it to show markers on the map and with that timeouts I have my app map works slower than it can be. That's why I need some callback prop like ```onFilteringEnd```

**Comment by iyegoroff** [comment]
If you really need this feature - feel free to implement it and open pull request.

**Comment by iyegoroff** [comment]
Closing, this is now out of [scope](https://github.com/iyegoroff/react-native-color-matrix-image-filters#scope).
