### ISSUE TITLE
Image sometimes not showing if defaultSource set

### ISSUE THREAD

**Issue by marcelschulze** [iyegoroff/react-native-color-matrix-image-filters#26]
Tested on iOS, RN 61.2, simulator and real device.

It works perfectly as long as I do not set the `defaultSource` prop on the `Image` component of React Native. 

After requiring some local picture for the `defaultSource`, some of the images do not show up anymore. It is totally random and always other pictures are affected. Around 10-20% of the pictures.

```
<ColorMatrix matrix={concatColorMatrices([grayscale(props.grayscale)])}>
      <Image defaultSource={placeholder} {...props} />
 </ColorMatrix>
```

Maybe it tries to apply it to the defaultSource first and then caches it, not sure about the internals of this Library. Adding the `ColorMatrix` only after `onLoad` didn't help either.
Because of that, I had to remove this filters for now.

Thanks for this cool Library and your support!

**Comment by iyegoroff** [comment]
Thanks for your feedback, @marcelschulze !

Does this behavior replicate on Android?
Probably this could be fixed by using two images instead of an image & defaultSource.
If you will manage to resolve this issue, feel free to share your workaround here or open a pull request.

**Comment by marcelschulze** [comment]
Good idea, I got it working like this:
```
<ImageBackground defaultSource={placeholder} {...props} source={undefined}>
      <ColorMatrix matrix={concatColorMatrices([grayscale(props.grayscale)])}>
          <Image {...props} />
      </ColorMatrix>
</ImageBackground>
```
