### ISSUE TITLE
How to get base64 or save the image with filters applied on it?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [iyegoroff/react-native-color-matrix-image-filters#30]
How to get base64 or save the image with filters applied on it on both android and iOS?

**Comment by iyegoroff** [comment]
This is not supported by rncmif. But you can use [react-native-image-filter-kit](https://github.com/iyegoroff/react-native-image-filter-kit/blob/master/docs/image_extraction.md) instead.
