### ISSUE TITLE
Declaration of 'RCTResizeMode' must be imported from module 'React.RCTGIFImageDecoder' before it is required

### ISSUE THREAD

**Issue by enzomanuelmangano** [iyegoroff/react-native-color-matrix-image-filters#32]
I'm using react-native: 0.59.9 and react-native-color-matrix-image-filters: 5.2.4. 
I notice that problem after adding use_modular_headers to the Podfile on iOS: **Declaration of 'RCTResizeMode' must be imported from module 'React.RCTGIFImageDecoder' before it is required**

Actually I solved that problem by removing`#import <React/RCTResizeMode.h>` from CMIFResizable.h

**Comment by iyegoroff** [comment]
Fixed in v5.2.5
