### ISSUE TITLE
How to add sketch effect?

### ISSUE THREAD

**Issue by WeTruck** [iyegoroff/react-native-color-matrix-image-filters#37]
Hi,

Thanks for the library.

I want **sketch** effect in my image.

Like this,

**Original:**
![image](https://user-images.githubusercontent.com/46923165/97727185-52e7c800-1afa-11eb-9e92-1596bda98a3c.png)

**Sketched:**
![image](https://user-images.githubusercontent.com/46923165/97727219-5ed38a00-1afa-11eb-9a64-a507703f24c0.png)

How can I do this? Please help.
Thanks in advance.

**Comment by iyegoroff** [comment]
Sketch effect is not supported.
