### ISSUE TITLE
"CMIFColorMatrixImageFilter" was not found in the UIManager

### ISSUE THREAD

**Issue by frapontillo** [iyegoroff/react-native-color-matrix-image-filters#41]
- Mobile platform: Android
- React Native 0.63.3
- react-native-color-matrix-image-filters: 5.2.10

I have just added the library to a RN project, and I get:

```
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.
This error is located at:
    in CMIFColorMatrixImageFilter (at native-filter.js:12)
    in ForwardRef (at color-matrix-filter.js:16)
    in ColorMatrix (at color-matrix-filter.js:69)
    in Grayscale (at Photo.tsx:64)
    in RCTView (at View.js:34)
```

It looks like `ColorMatrixImageFilterManager.java` doesn't get picked up as a module.
Is this a bug in the library or do I have anything misconfigured?

**Comment by frapontillo** [comment]
**Solved**: the issue was that I added this library onto another library, which was then used in the main app.
At the moment, RN doesn't auto-link transitive dependencies, so I also add to add `react-native-color-matrix-image-filters` to my main app's dependencies as well (see https://github.com/react-native-community/cli/issues/870).

Hope this is useful for someone else.

**Comment by ytt123** [comment]
can not get it ,can you take  react-native-color-matrix-image-filters  as an example about your project?
