### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by boldwade** [iyegoroff/react-native-color-matrix-image-filters#57]
I'm on RN 64.2 with rn-color-matrix-image-filters 5.2.10. I'm not seeing any image being altered in any way.

I'm on android running on emulator. Yes, I have run a clean build and install, a couple of times. 

I've tried wrapping a fast image without seeing any difference in the output:
```
<Grayscale>
    <FastImage
        onError={this.onError}
        onLoadEnd={this.onLoadEnd}
        resizeMode={this.props.resizeMode ?? 'cover'}
        source={source}
        style={this.props.style}
    />
</Grayscale>
```

I've tried simply using the rn image with grayscale and other filters, without seeing any difference in output:
```
<ColorMatrix
    matrix={concatColorMatrices([saturate(-0.9), contrast(5.2), invert()])}
>
    <Image source={this.getSource()} style={this.props.style} />
</ColorMatrix>

```

Neither of which actually seems to do anything to the image.
What am I doing wrong?

**Comment by iyegoroff** [comment]
Can you check it on a real device? Probably that is just an emulator issue.

**Comment by boldwade** [comment]
Sorry man... we are doing some crazy things ourselves with modifying pixel color and was apparently clashing with your library.. problem was on our end...
