### ISSUE TITLE
Looks like ColorMatrix not working for iOS

### ISSUE THREAD

**Issue by nikhilameriya** [iyegoroff/react-native-color-matrix-image-filters#61]
Basic ColorMatrix code is inverting images on Android but not on iOS device.

<ColorMatrix matrix={invert()}>
 <Image {...imageProps} /> 
</ColorMatrix>
It's doing nothing on iOS for me.

Running through Xcode version 13.0(Beta) and on ios version 14.7.1.
It's possible to have issue due to the iOS > 14 version.

**Comment by iyegoroff** [comment]
Just checked rnifk v5.2.10 & rn v0.67.3 - everything works as expected for me on iOS and android. If you still have problems with this module, please create a minimal repro.
