### ISSUE TITLE
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager

### ISSUE THREAD

**Issue by dragma** [iyegoroff/react-native-color-matrix-image-filters#64]
Hello 
I have this error (on android, not tested yet on iOS)
`Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager`

cleaning the cache or graddle didn't do the tricks.

package.json
```
"react-native": "0.66.4",
"react-native-color-matrix-image-filters": "^5.2.10",
```

The error output :
```
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.

This error is located at:
    in CMIFColorMatrixImageFilter (at native-filter.js:12)
    ....
```

I don't thinks I missed a step during installation. I event execute the `react-native link` command to be sure.

Thaks :)

**Comment by jakrim** [comment]
I have the same issue using react native v 0.64.3

**Comment by Piero87** [comment]
hello @iyegoroff, I have the same problem here with last version of react native 0.67.2, can you please help us?

**Comment by iyegoroff** [comment]
Just checked rnifk v5.2.10 & rn v0.67.3 - everything works as expected for me on iOS and android. If you still have problems with this module, please create a minimal repro.
