### ISSUE TITLE
"RNColorMatrixImageFilter" was not found in the UIManager

### ISSUE THREAD

**Issue by sbtly** [iyegoroff/react-native-color-matrix-image-filters#7]
After installing with "yarn add" and linking with "react-native link", I got this error.
<img width="559" alt="2018-10-01 10 00 57" src="https://user-images.githubusercontent.com/16576590/46290086-ce968400-c5c5-11e8-826e-2c91d1a230d4.png">

I tried reinstalling, Xcode manual linking, but nothing seems to fix it.

My react native version is 0.57.1.

**Comment by iyegoroff** [comment]
Try cleaning the project in Xcode.

**Comment by sbtly** [comment]
Could you define "cleaning the project" in Xcode?

**Comment by iyegoroff** [comment]
http://i.stack.imgur.com/AFqWF.png

**Comment by sbtly** [comment]
Thank you for the quick reply!

**Comment by wawrzy** [comment]
Hi,

I'm facing the same issue on ReactNative 0.57.2. 
But clean Xcode project doesn't work.

Any ideas ?

**Comment by sbtly** [comment]
Hi! After cleaning in Xcode, I also did the following steps.
[https://github.com/react-community/react-native-maps/issues/2495#issuecomment-425773235](url)
