### ISSUE TITLE
Can not save image after setting greyscale to image || react-native-color-matrix-image-filters

### ISSUE THREAD

**Issue by NTJ3** [iyegoroff/react-native-color-matrix-image-filters#70]
@iyegoroff There is no way to save an image after setting the filter matrix.

[react-native-color-matrix-image-filters](https://github.com/iyegoroff/react-native-color-matrix-image-filters)

**Comment by iyegoroff** [comment]
Yes. This module can't save image files. See the [scope](../#scope).
