### ISSUE TITLE
Not auto linked on ios

### ISSUE THREAD

**Issue by skanger** [iyegoroff/react-native-color-matrix-image-filters#86]
Description：

CMIFColorMatrixImageFilter was not found in the UIManager.

Android work perfect, ios report this message.

react-native link 'react-native-color-matrix-image-filters' only link Android.

use pod install , no error occured, but nothing related in podfile and podfile.lock

i do not use 'expo'

Can you help me to make ios run success?

Environment
System:
OS: macOS 13.0.1
CPU: (8) arm64 Apple M1
Memory: 117.45 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
Yarn: 1.22.18 - /opt/homebrew/bin/yarn
npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
Android SDK: Not Found
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8609683
Xcode: 14.1/14B47b - /usr/bin/xcodebuild
Languages:
Java: 11.0.15 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.67.5 => 0.67.5
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

**Comment by skanger** [comment]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/18080860/205846053-24146463-ecd4-413c-b53c-e86fc6f6ea04.png">

    "react-native-color-matrix-image-filters": "^6.0.1",

**Comment by kimak** [comment]
Same issue, RNColorMatrixImageFilters is automatically removed when doing pod install
![Screenshot 2022-12-06 at 11 10 16](https://user-images.githubusercontent.com/1573707/205882555-aef8dbca-7b00-4985-a67c-2a356327f0a0.png)

**Comment by lwrr** [comment]
> Description：
> 
> CMIFColorMatrixImageFilter was not found in the UIManager.
> 
> Android work perfect, ios report this message.
> 
> react-native link 'react-native-color-matrix-image-filters' only link Android.
> 
> use pod install , no error occured, but nothing related in podfile and podfile.lock
> 
> i do not use 'expo'
> 
> Can you help me to make ios run success?
> 
> Environment System: OS: macOS 13.0.1 CPU: (8) arm64 Apple M1 Memory: 117.45 MB / 16.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node Yarn: 1.22.18 - /opt/homebrew/bin/yarn npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.11.3 - /opt/homebrew/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: 2021.2 AI-212.5712.43.2112.8609683 Xcode: 14.1/14B47b - /usr/bin/xcodebuild Languages: Java: 11.0.15 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 17.0.2 => 17.0.2 react-native: 0.67.5 => 0.67.5 react-native-macos: Not Found npmGlobalPackages: react-native: Not Found

1  add the following line to your Podfile:
  pod 'react-native-color-matrix-image-filters', :path => '../node_modules/react-native-color-matrix-image-filters/react-native-color-matrix-image-filters.podspec'
  
  2 cd ios && pod install && cd ..

**Comment by skanger** [comment]
so much thanks .

it works.

I am confused why ios need do it by manual, android do not.


Maybe it can be add to README.md to help others.


> > Description：
> > CMIFColorMatrixImageFilter was not found in the UIManager.
> > Android work perfect, ios report this message.
> > react-native link 'react-native-color-matrix-image-filters' only link Android.
> > use pod install , no error occured, but nothing related in podfile and podfile.lock
> > i do not use 'expo'
> > Can you help me to make ios run success?
> > Environment System: OS: macOS 13.0.1 CPU: (8) arm64 Apple M1 Memory: 117.45 MB / 16.00 GB Shell: 5.8.1 - /bin/zsh Binaries: Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node Yarn: 1.22.18 - /opt/homebrew/bin/yarn npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.11.3 - /opt/homebrew/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1 Android SDK: Not Found IDEs: Android Studio: 2021.2 AI-212.5712.43.2112.8609683 Xcode: 14.1/14B47b - /usr/bin/xcodebuild Languages: Java: 11.0.15 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: 17.0.2 => 17.0.2 react-native: 0.67.5 => 0.67.5 react-native-macos: Not Found npmGlobalPackages: react-native: Not Found
> 
> 1 add the following line to your Podfile: pod 'react-native-color-matrix-image-filters', :path => '../node_modules/react-native-color-matrix-image-filters/react-native-color-matrix-image-filters.podspec'
> 
> 2 cd ios && pod install && cd ..

**Comment by iyegoroff** [comment]
@skanger @lwrr , not sure why did you need to edit Podfile manually - I just checked on a fresh app and `npx pod-install` worked correctly.

@kimak there is a breaking change when upgrading from v5 to v6 - pod was renamed from `RNColorMatrixImageFilters` to `react-native-color-matrix-image-filters`, so you need to uninstall the package, run `npx pod-install`, install latest version of this package, then run `npx pod-install` again and you will see correct names and versions in your Podfile.lock.

**Comment by bryantobing12** [comment]
still facing the same issue

- uninstall package
- reinstall package
- run `npx pod-install`

still get this error on ios 
![Screenshot 2022-12-22 at 13 15 43](https://user-images.githubusercontent.com/46083126/209069563-b8e2cf06-b7e1-4fc5-aaf3-cf8eff40183e.png)

**Comment by bryantobing12** [comment]
> pod 'react-native-color-matrix-image-filters', :path => '../node_modules/react-native-color-matrix-image-filters/react-native-color-matrix-image-filters.podspec'

adding the above code to `podfile` somehow helps,
