### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & ViewProps & { readonly amount?: number | undefined; } & RefAttributes<View>'.

### ISSUE THREAD

**Issue by kimak** [iyegoroff/react-native-color-matrix-image-filters#87]
- Versions: 

> react-native@0.67.5
> react-native-color-matrix-image@6.0.1

- Typescript issue
```
Property 'children' does not exist on type 'IntrinsicAttributes & ViewProps & { readonly amount?: number | undefined; } & RefAttributes<View>'.
```

- Code example:
```
      <Grayscale
            amount={1 : 0}
          >
            <ImageBackground
              source={imageSource}
            />
          </Grayscale>
 ```     
      
- Screenshot:
      
![Screenshot 2022-12-06 at 11 12 46](https://user-images.githubusercontent.com/1573707/205883700-759d9fc4-fff2-4d5a-b333-fcacd3f1215c.png)

**Comment by iyegoroff** [comment]
You are probably using an old version of `@types/react` package. I don't see this error with `^18.0.26`.
